language: java
jdk:
  - openjdk14

# используем режим обычного пользователя для сборки проекта.
sudo: false

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонний сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почту если сборка упала
notifications:
  email:
    recipients:

    on_success: never # default: change
    on_failure: always # default: always

    env:
      global:
        - CODECOV_TOKEN="6401d1b9-9f00-47bc-a71c-9ae8dca75225"